title: Thorough analysis of PCIe Gen3 Communication
booktitle: Poster Session D in 2017 International Conference on Reconfigurable
  Computing and FPGAs(ReConFig 2017)
year: 2017
authors:
  - Hiroki Nakamura
  - Hirotaka Takayama
  - Yoshiki Yamaguchi
  - Taisuke Boku
bibtex: >-
  @inproceedings { ReConFig2017:hnakamura,
  	author	= "{Hiroki Nakamura} and {Hirotaka Takayama} and {Yoshiki Yamaguchi} and {Taisuke Boku}",
  	title	= "{Thorough analysis of PCIe Gen3 Communication}",
  	booktitle = "Poster Session D in 2017 International Conference on Reconfigurable Computing and FPGAs(ReConFig 2017)",
  	month	= "12",
  	year	= "2017"
  }
reference: "Hiroki Nakamura, Hirotaka Takayama, Yoshiki Yamaguchi, Taisuke Boku:
  “Thorough analysis of PCIe Gen3 Communication”, Poster Session D in 2017
  International Conference on Reconfigurable Computing and FPGAs(ReConFig 2017),
  Dec. 2017."
class:
  class: international
  subclass: poster
