services:
  traefik:
    image: traefik:3.0
    command: --configFile=/etc/traefik/traefik.yaml
    volumes:
      - type: bind
        source: ./traefik
        target: /etc/traefik
      - type: bind
        source: /etc/pki/www
        target: /etc/pki/www
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443/tcp"
      - "443:443/udp"
  fallback:
    build: ./fallback
    volumes:
      - type: bind
        source: /home
        target: /home
    labels:
      - traefik.enable=true
      - traefik.http.routers.fallback.entrypoints=https,http
      - traefik.http.routers.fallback.rule=Host(`www.hpcs.cs.tsukuba.ac.jp`)
      - traefik.http.routers.fallback.priority=1
      - traefik.http.routers.fallback.tls.certresolver=main
      - traefik.http.routers.fallback.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true
  hpcs-web:
    image: nginx:1.25.4
    volumes:
      - type: bind
        source: ./hpcs-web/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ../dist
        target: /www
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.entrypoints=https
      - traefik.http.routers.web.priority=100
      - traefik.http.routers.web.tls.certresolver=main
      - >
        traefik.http.routers.web.rule=Host(`www.hpcs.cs.tsukuba.ac.jp`) && (
        Path(`/`)
        || Path(`/index.html`)
        || Path(`/global.css`)
        || Path(`/destyle.css`)
        || Path(`/favicon.svg`)
        || PathPrefix(`/_astro/`)
        || PathPrefix(`/access/`)
        || Path(`/access`)
        || PathPrefix(`/bachelor/`)
        || Path(`/bachelor`)
        || PathPrefix(`/members/`)
        || Path(`/members`)
        || PathPrefix(`/news/`)
        || Path(`/news`)
        || PathPrefix(`/publications/`)
        || Path(`/publications`)
        || PathPrefix(`/teams/`)
        || Path(`/teams`)
        )
