http:
  routers:
    cfp-summary-server:
      rule: PathPrefix(`/internal/netteam/cfps`)
      priority: 100
      service: cfp-summary-server
      entrypoints:
        - https
      middlewares:
        - cfp-summary-server-redirect@file
        - cfp-summary-server@file
  middlewares:
    cfp-summary-server:
      stripprefix:
        prefixes:
          - /internal/netteam/cfps
    cfp-summary-server-redirect:
      redirectregex:
        regex: ^https://www.hpcs.cs.tsukuba.ac.jp/internal/netteam/cfps$
        replacement: https://www.hpcs.cs.tsukuba.ac.jp/internal/netteam/cfps/
        permanent: true
  services:
    cfp-summary-server:
      loadBalancer:
        servers:
          - url: http://172.16.0.2:8443
