name: Docker Build and Push

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read
  packages: write
  actions: read

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push images
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ghcr.io/hpcslab/web:${{ github.sha }}
          push: true
